# build stage
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm i react-google-recaptcha
COPY . .

# dev stage
EXPOSE 5173
ENV CHOKIDAR_USEPOLLING=true
CMD ["npm", "run", "dev"]
