from .aluno_repository import AlunoRepository
from .sala_repository import SalaRepository
from .docente_repository import DocenteRepository
from .notificacao_repository import NotificacaoRepository
from .horario_repository import HorarioRepository
from .turma_repository import TurmaRepository